general.import = [
  "~/.config/alacritty/alacritty-theme/themes/monokai_charcoal.toml",
  # "~/.config/alacritty/alacritty-theme/themes/xterm.toml"
]

# [[hints.enabled]]
# mouse.enabled = true

[window]
opacity = 0.86

padding.x = 0
padding.y = 0

decorations = "Full"
decorations_theme_variant = "Light" # "Dark"
startup_mode = "Maximized"

option_as_alt = "OnlyLeft"

[font]
size = 12
# normal.family= "JetBrains Mono"
# normal.style= "Regular"
# bold.family= "JetBrains Mono"
# bold.style= "Bold"
# italic.family= "JetBrains Mono"
# italic.style= "Italic"
# bold_italic.family= "JetBrains Mono"
# bold_italic.style= "Bold Italic"

normal.family = "FiraCode Nerd Font"
normal.style = "Medium"
bold.family = "FiraCode Nerd Font"
bold.style = "Bold"
italic.family = "FiraCode Nerd Font"
italic.style = "Italic"
bold_italic.family = "FiraCode Nerd Font"
bold_italic.style = "Bold Italic"

# normal.family= "MesloLGS Nerd Font Mono"
# normal.style= "Medium"
# bold.family= "MesloLGS Nerd Font Mono"
# bold.style= "Bold"
# italic.family= "MesloLGS Nerd Font Mono"
# italic.style= "Italic"
# bold_italic.family= "MesloLGS Nerd Font Mono"
# bold_italic.style= "Bold Italic"
